# Generated by Django 3.0.7 on 2021-01-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="about",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="when",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="event",
            name="you",
            field=models.TextField(default=""),
        ),
    ]
