# Generated by Django 3.0.7 on 2021-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_auto_20210103_1602"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="reg_link",
            field=models.TextField(default=""),
        ),
    ]
