# Generated by Django 3.0.7 on 2021-01-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_reg_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="reg_link",
            field=models.TextField(blank=True, default=""),
        ),
    ]
