# Generated by Django 3.0.7 on 2021-01-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Core_committee",
            fields=[
                ("name", models.CharField(max_length=255)),
                ("post", models.CharField(max_length=255)),
                ("pic", models.ImageField(upload_to="images/team")),
                ("position", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
