# Generated by Django 3.0.7 on 2021-02-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210212_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paragraph',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
    ]
