# Generated by Django 3.0.7 on 2021-01-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemStatements",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("soln_type", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("company_logo", models.ImageField(upload_to="images/loc/statements")),
            ],
        ),
        migrations.CreateModel(
            name="Sponsors",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(upload_to="images/loc/sponsors")),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
    ]
