# Generated by Django 3.1.5 on 2021-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='url',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
