# Generated by Django 3.1.5 on 2021-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0002_sponsors_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
