# Generated by Django 3.1.5 on 2021-03-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0003_auto_20210302_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='partner_type',
            field=models.CharField(choices=[('Tech Partner', 'Tech Partner'), ('Power Sponsor', 'Power Sponsor'), ('Associate Sponsor', 'Associate Sponsor'), ('Gifting Partner', 'Gifting Partner')], default='Tech Partner', max_length=200),
        ),
    ]
