# Generated by Django 3.1.7 on 2021-03-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loc', '0004_sponsors_partner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsors',
            name='partner_type',
            field=models.CharField(choices=[('Tech Partner', 'Tech Partner'), ('Power Sponsor', 'Power Sponsor'), ('Associate Sponsor', 'Associate Sponsor'), ('Gifting Partner', 'Gifting Partner'), ('Education Abroad Partner', 'Education Abroad Partner')], default='Tech Partner', max_length=200),
        ),
    ]
