# Generated by Django 3.1.7 on 2021-03-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('positionType', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FormStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('sap_id', models.CharField(max_length=11, unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('email_id', models.EmailField(max_length=150)),
                ('phone_no', models.CharField(max_length=10)),
                ('whatsapp_no', models.CharField(max_length=10)),
                ('resume_drive_link', models.URLField(max_length=500)),
                ('department', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=50)),
                ('is_member', models.BooleanField(default=False)),
                ('amount', models.CharField(max_length=5)),
                ('payment_verified', models.BooleanField(default=False)),
                ('no_of_companies', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=100, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='if.formstudent')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='if.formcompany')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='if.formstudent')),
            ],
        ),
    ]
