# Generated by Django 3.1.7 on 2021-03-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0002_form_formcompany_formstudent_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstudent',
            name='payment_receipt',
            field=models.FileField(default=0, upload_to='images/if_receipt'),
            preserve_default=False,
        ),
    ]
