# Generated by Django 3.1.7 on 2021-03-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0005_remove_formstudent_stu_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formstudent',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='images/if_receipt'),
        ),
    ]
