# Generated by Django 3.1.7 on 2021-04-02 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0006_auto_20210330_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='job_requirement',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='stipend',
            field=models.CharField(max_length=100),
        ),
    ]
