# Generated by Django 3.1.7 on 2021-04-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0007_auto_20210402_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='role',
            field=models.CharField(max_length=1255),
        ),
    ]
