# Generated by Django 3.1.7 on 2021-04-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0009_auto_20210402_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='mode_of_internship',
            field=models.CharField(default='edit this', max_length=50),
            preserve_default=False,
        ),
    ]
