# Generated by Django 3.1.7 on 2021-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0010_companies_mode_of_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='mode_of_internship',
            field=models.CharField(max_length=100),
        ),
    ]
