# Generated by Django 3.1.7 on 2021-04-11 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0011_auto_20210402_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='attended',
            field=models.BooleanField(default=True),
        ),
    ]
