# Generated by Django 3.1.7 on 2021-04-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('if', '0012_form_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='formstudent',
            name='refund_amount',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='formstudent',
            name='refund_saved',
            field=models.BooleanField(default=False),
        ),
    ]
